apy_data_grid:
  theme: 'datagrid/blocks_js_bs3.jquery.html.twig'
  persistence: true
  no_data_message: false
  no_result_message: Aucune donnée.
  pagerfanta:
    enable: true    #default false
    view_class: Pagerfanta\View\TwitterBootstrap5View #default    Pagerfanta\View\DefaultView
    options:            #all options of pager fanta view constructor
      prev_message : «
      next_message : »
