monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

# installation de symfony_mailer et l'ajout des 3 variables d'environnements necessaires
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            grouped:
                type: group
                members: [ streamed, deduplicated ]
            streamed:
                type: rotating_file
                max_files: 90
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            deduplicated:
                type: deduplication
                handler: symfony_mailer
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            symfony_mailer:
                type: symfony_mailer
                from_email: '%env(EMAIL_SENDER)%'
                to_email: '%env(EMAIL_TECHNIQUE)%'
                subject: 'Erreur %env(EMAIL_ERROR_SUBJECT)% - %%message%%'
                level: debug
                formatter: monolog.formatter.html
                content_type: text/html
                
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

