twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        kernelRootDir: "%kernel.project_dir%"
        application_name:  "%env(APPLICATION_NAME)%"
when@test:
    twig:
        strict_variables: true