framework:
  messenger:
    transports:
      sync: "sync://"
    routing:
      # Route your messages to the transports
      # 'App\Message\YourMessage': async
      'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
